# Generated by Django 4.1.2 on 2022-11-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('series_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriescategory',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='source.source'),
        ),
        migrations.AlterUniqueTogether(
            name='seriescategory',
            unique_together={('source_id', 'external_id')},
        ),
    ]
