# Generated by Django 4.1.2 on 2022-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriescategory',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
