# Generated by Django 4.1.2 on 2022-11-27 11:55

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesIndex',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('config', systems.models.fields.DictionaryField(default=dict)),
                ('provider_type', models.CharField(default='base', max_length=128)),
                ('secrets', systems.models.fields.EncryptedDataField(default={})),
                ('variables', systems.models.fields.DictionaryField(default=dict, editable=False)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=500)),
                ('description', models.TextField(default=None, null=True)),
                ('units', models.CharField(default=None, max_length=256, null=True)),
                ('popularity', models.IntegerField(default=None, null=True)),
                ('end', models.DateField(default=None, null=True)),
                ('seasonal_adjustment', models.CharField(default=None, max_length=256, null=True)),
                ('frequency', models.CharField(default=None, max_length=256, null=True)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
                ('start', models.DateField(default=None, null=True)),
                ('series_categories', models.ManyToManyField(blank=True, related_name='%(data_name)s', to='series_category.seriescategory')),
            ],
            options={
                'verbose_name': 'series index',
                'verbose_name_plural': 'series indexes',
                'db_table': 'data_collection_series_index',
                'ordering': ['external_id'],
                'abstract': False,
            },
        ),
    ]
