# Generated by Django 4.1.2 on 2022-11-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesIndex',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('popularity', models.IntegerField(default=None, null=True)),
                ('units_short', models.CharField(default=None, max_length=256, null=True)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('start', models.DateField(default=None, null=True)),
                ('seasonal_adjustment_short', models.CharField(default=None, max_length=256, null=True)),
                ('seasonal_adjustment', models.CharField(default=None, max_length=256, null=True)),
                ('frequency', models.CharField(default=None, max_length=256, null=True)),
                ('frequency_short', models.CharField(default=None, max_length=256, null=True)),
                ('units', models.CharField(default=None, max_length=256, null=True)),
                ('end', models.DateField(default=None, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='source.source')),
            ],
            options={
                'verbose_name': 'series index',
                'verbose_name_plural': 'series indexes',
                'db_table': 'data_collection_series_index',
                'ordering': ['external_id'],
                'abstract': False,
                'unique_together': {('source_id', 'external_id')},
            },
        ),
    ]
