# Generated by Django 4.1.2 on 2022-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_category', '0001_initial'),
        ('series_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesindex',
            name='series_categories',
            field=models.ManyToManyField(blank=True, related_name='%(data_name)s', to='series_category.seriescategory'),
        ),
    ]
