# Generated by Django 4.1.2 on 2022-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_index', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesindex',
            name='external_id',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='seriesindex',
            name='name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
