# Generated by Django 4.1.2 on 2022-11-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series_index', '0002_seriesindex_series_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesindex',
            name='frequency_short',
        ),
        migrations.RemoveField(
            model_name='seriesindex',
            name='seasonal_adjustment_short',
        ),
        migrations.RemoveField(
            model_name='seriesindex',
            name='units_short',
        ),
    ]
