# Generated by Django 4.1.2 on 2022-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_index', '0003_remove_seriesindex_frequency_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesindex',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
