_base_model: &base_model
    admin_roles: [ data-admin ]
    view_roles: [ data-auditor ]


models:
    source:
        <<: *base_model
        base: name_resource
        command_base: source
        display: "<name>"
        priority: 50

    series_category:
        <<: *base_model
        base: source
        plural: series_categories
        id_fields: [ source_id, external_id ]
        key: external_id
        command_base: category
        display: "<source_id>-<external_id>"
        priority: 55
        fields:
            external_id:
                type: string
            parent:
                type: foreign_key
                options:
                    related_data_name: series_category
            description:
                type: text

    series_index:
        <<: *base_model
        base: source
        mixins: [ series_categories ]
        plural_suffix: es
        id_fields: [ source_id, external_id ]
        key: external_id
        name_field: false
        command_base: series
        display: "<source_id>-<external_id>"
        priority: 55
        fields:
            name:
                type: string
                options:
                    max_length: 500
                    nullable: false
            external_id:
                type: string
            description:
                type: text
            frequency:
                type: string
            units:
                type: string
            seasonal_adjustment:
                type: string
            popularity:
                type: integer
            start:
                type: date
            end:
                type: date
